"""E3-Hybrid Swarm Routing algorithm for dynamic EV urban routing.

This is the primary research contribution of the thesis, combining ACO, BCO, and PSO
into a parallel cooperative ensemble using a centralized Information Blackboard.

The algorithm uses Composition over Inheritance, maintaining completely independent
ACO, BCO, and PSO engines and orchestrating them via the IterativeSwarmEngine protocol.
"""

import time
from dataclasses import dataclass, field
from typing import Any

from src.routing.aco import ACORouter
from src.routing.base_swarm import SwarmIterationResult
from src.routing.bco import BCORouter
from src.routing.exceptions import InvalidNodeError, NoPathFoundError
from src.routing.pso import PSORouter
from src.routing.router import Router
from src.routing.routing_context import RoutingContext
from src.routing.routing_result import RoutingResult
from src.routing.scorer import MultiObjectiveEdgeScorer
from src.utils.config import AlgorithmConfig


@dataclass
class E3HybridIterationMetrics:
    """Per-iteration diagnostics for the E3-Hybrid search."""

    iteration: int
    global_best_cost: float
    gbest_source: str  # 'ACO', 'BCO', 'PSO', or 'None'

    # Number of valid routes generated by each subsystem this iteration
    aco_valid_routes: int
    bco_valid_routes: int
    pso_valid_routes: int

    # Percentage contribution to valid routes this iteration
    aco_contribution: float
    bco_contribution: float
    pso_contribution: float


@dataclass
class E3HybridSearchMetrics:
    """Aggregate metrics for a single Hybrid find_route() call."""

    query_origin: str
    query_destination: str
    num_iterations_run: int
    convergence_iteration: int
    best_cost_found: float
    gbest_source: str

    # Overall contributions
    aco_total_valid_routes: int = 0
    bco_total_valid_routes: int = 0
    pso_total_valid_routes: int = 0

    # Time to adapt after a disruption (measured in iterations needed to find a new gbest)
    adaptation_iterations: int = 0

    iteration_records: list[E3HybridIterationMetrics] = field(default_factory=list)


class E3HybridRouter(Router):
    """The E3-Hybrid Cooperative Swarm Router."""

    def __init__(
        self,
        config: AlgorithmConfig,
        scorer: MultiObjectiveEdgeScorer | None = None,
        seed: int | None = None,
    ) -> None:
        """Initialises the hybrid router and its sub-engines."""
        self.config = config
        self.hybrid_config = config.e3_hybrid

        # Shared heuristic evaluator
        self.scorer = scorer or MultiObjectiveEdgeScorer(config.objectives)

        # Instantiate sub-engines. They share the same seed to guarantee deterministic runs.
        self.aco = ACORouter(config.aco, scorer=self.scorer, seed=seed)
        self.bco = BCORouter(config.bco, scorer=self.scorer, seed=seed)
        self.pso = PSORouter(config.pso, scorer=self.scorer, seed=seed)

        # Hybrid Blackboard State
        self.gbest_cost: float = float("inf")
        self.gbest_nodes: list[str] = []
        self.gbest_edges: list[str] = []
        self.gbest_source: str = "None"
        self._environment_dirty: bool = False

        # Telemetry
        self.search_count: int = 0
        self.total_search_time: float = 0.0
        self.total_expanded_nodes: int = 0
        self.metrics_history: list[E3HybridSearchMetrics] = []

    def find_route(
        self,
        origin_node_id: str,
        destination_node_id: str,
        context: RoutingContext,
    ) -> RoutingResult:
        """Finds a highly optimized route using the cooperative swarm ensemble."""
        self.search_count += 1
        start_wall = time.perf_counter()

        self._validate_nodes(origin_node_id, destination_node_id, context)

        if origin_node_id == destination_node_id:
            return self._trivial_result(origin_node_id, start_wall)

        if self._environment_dirty:
            self._re_evaluate_gbest(context)
            self._environment_dirty = False

        # Initialize engines
        self.aco.initialize_search(origin_node_id, destination_node_id, context)
        self.bco.initialize_search(origin_node_id, destination_node_id, context)
        self.pso.initialize_search(origin_node_id, destination_node_id, context)

        # Information Sharing Phase 0: ACO -> PSO
        if self.hybrid_config.share_aco_to_pso:
            pheromones = self.aco.get_pheromone_matrix()
            if pheromones:
                self.pso.inject_pheromone_matrix(pheromones)

        metrics: E3HybridSearchMetrics | None = None
        if self.hybrid_config.collect_metrics:
            metrics = E3HybridSearchMetrics(
                query_origin=origin_node_id,
                query_destination=destination_node_id,
                num_iterations_run=0,
                convergence_iteration=0,
                best_cost_found=float("inf"),
                gbest_source="None",
            )

        conv_iter = 0
        query_best_cost = float("inf")
        total_expanded = 0

        for iteration in range(self.hybrid_config.max_iterations):
            # 1. Execute Independent Swarm Steps
            aco_res = self.aco.execute_iteration(
                origin_node_id, destination_node_id, context
            )
            bco_res = self.bco.execute_iteration(
                origin_node_id, destination_node_id, context
            )
            pso_res = self.pso.execute_iteration(
                origin_node_id, destination_node_id, context
            )

            total_expanded += (
                aco_res.nodes_expanded + bco_res.nodes_expanded + pso_res.nodes_expanded
            )

            aco_valid = [c for c in aco_res.costs if c < float("inf")]
            bco_valid = [c for c in bco_res.costs if c < float("inf")]
            pso_valid = [c for c in pso_res.costs if c < float("inf")]

            n_aco = len(aco_valid)
            n_bco = len(bco_valid)
            n_pso = len(pso_valid)
            total_valid = n_aco + n_bco + n_pso

            if metrics:
                metrics.aco_total_valid_routes += n_aco
                metrics.bco_total_valid_routes += n_bco
                metrics.pso_total_valid_routes += n_pso

            # 2. Evaluate Blackboard
            iter_best_cost = float("inf")
            iter_best_nodes: list[str] = []
            iter_best_edges: list[str] = []
            iter_best_source = "None"

            # Helper to check paths
            def check_paths(res: SwarmIterationResult, source: str) -> None:
                nonlocal \
                    iter_best_cost, \
                    iter_best_nodes, \
                    iter_best_edges, \
                    iter_best_source
                for nodes, edges, cost in zip(
                    res.path_nodes, res.path_edges, res.costs
                ):
                    if cost < iter_best_cost:
                        iter_best_cost = cost
                        iter_best_nodes = nodes
                        iter_best_edges = edges
                        iter_best_source = source

            check_paths(aco_res, "ACO")
            check_paths(bco_res, "BCO")
            check_paths(pso_res, "PSO")

            # Update Global Blackboard Best
            if iter_best_cost < self.gbest_cost:
                self.gbest_cost = iter_best_cost
                self.gbest_nodes = list(iter_best_nodes)
                self.gbest_edges = list(iter_best_edges)
                self.gbest_source = iter_best_source

            if self.gbest_cost < query_best_cost:
                query_best_cost = self.gbest_cost
                conv_iter = iteration

            # 3. Synchronize Blackboard via Ablation Toggles
            if self.gbest_edges:
                if self.hybrid_config.share_bco_pso_to_aco:
                    self.aco.inject_global_best(
                        self.gbest_nodes, self.gbest_edges, self.gbest_cost
                    )
                if self.hybrid_config.share_gbest_to_bco:
                    self.bco.inject_global_best(
                        self.gbest_nodes, self.gbest_edges, self.gbest_cost
                    )
                if self.hybrid_config.share_gbest_to_pso:
                    self.pso.inject_global_best(
                        self.gbest_nodes, self.gbest_edges, self.gbest_cost
                    )

            # Record metrics
            if metrics:
                metrics.iteration_records.append(
                    E3HybridIterationMetrics(
                        iteration=iteration,
                        global_best_cost=self.gbest_cost,
                        gbest_source=self.gbest_source,
                        aco_valid_routes=n_aco,
                        bco_valid_routes=n_bco,
                        pso_valid_routes=n_pso,
                        aco_contribution=n_aco / total_valid
                        if total_valid > 0
                        else 0.0,
                        bco_contribution=n_bco / total_valid
                        if total_valid > 0
                        else 0.0,
                        pso_contribution=n_pso / total_valid
                        if total_valid > 0
                        else 0.0,
                    )
                )

        if not self.gbest_nodes or self.gbest_cost == float("inf"):
            raise NoPathFoundError(
                f"E3-Hybrid could not find a path from '{origin_node_id}' to "
                f"'{destination_node_id}'."
            )

        if metrics:
            metrics.num_iterations_run = self.hybrid_config.max_iterations
            metrics.convergence_iteration = conv_iter
            metrics.best_cost_found = self.gbest_cost
            metrics.gbest_source = self.gbest_source
            self.metrics_history.append(metrics)

        elapsed = time.perf_counter() - start_wall
        self.total_search_time += elapsed
        self.total_expanded_nodes += total_expanded

        return RoutingResult(
            path_nodes=self.gbest_nodes,
            path_edges=self.gbest_edges,
            total_cost=self.gbest_cost,
            expanded_nodes=total_expanded,
            search_time_s=elapsed,
        )

    def update_network(self, network_update: Any) -> None:
        """Propagates network changes to all engines."""
        self.aco.update_network(network_update)
        self.bco.update_network(network_update)
        self.pso.update_network(network_update)
        self._environment_dirty = True

    def reset(self) -> None:
        """Resets the Hybrid state and all sub-engines."""
        self.aco.reset()
        self.bco.reset()
        self.pso.reset()

        self.gbest_cost = float("inf")
        self.gbest_nodes = []
        self.gbest_edges = []
        self.gbest_source = "None"
        self._environment_dirty = False

        self.search_count = 0
        self.total_search_time = 0.0
        self.total_expanded_nodes = 0
        self.metrics_history.clear()

    def get_statistics(self) -> dict[str, Any]:
        """Returns hybrid telemetry and sub-engine stats."""
        return {
            "algorithm": "E3-Hybrid",
            "search_count": self.search_count,
            "total_search_time_s": self.total_search_time,
            "avg_search_time_s": (
                self.total_search_time / self.search_count
                if self.search_count > 0
                else 0.0
            ),
            "total_expanded_nodes": self.total_expanded_nodes,
            "global_best_cost": self.gbest_cost,
            "global_best_source": self.gbest_source,
            "metrics_records": len(self.metrics_history),
            "subsystems": {
                "aco": self.aco.get_statistics(),
                "bco": self.bco.get_statistics(),
                "pso": self.pso.get_statistics(),
            },
        }

    def _validate_nodes(
        self, origin_node_id: str, destination_node_id: str, context: RoutingContext
    ) -> None:
        if origin_node_id not in context.network.nodes:
            raise InvalidNodeError(f"Origin '{origin_node_id}' not in network.")
        if destination_node_id not in context.network.nodes:
            raise InvalidNodeError(f"Destination '{destination_node_id}' not found.")

    def _trivial_result(self, node_id: str, start_wall: float) -> RoutingResult:
        elapsed = time.perf_counter() - start_wall
        self.total_search_time += elapsed
        return RoutingResult(
            path_nodes=[node_id],
            path_edges=[],
            total_cost=0.0,
            expanded_nodes=0,
            search_time_s=elapsed,
        )

    def _re_evaluate_gbest(self, context: RoutingContext) -> None:
        """Re-evaluates the cached global best path."""
        if not self.gbest_edges:
            return

        cost = 0.0
        net = context.network
        veh = context.vehicle
        for eid in self.gbest_edges:
            if eid not in net.edges:
                cost = float("inf")
                break
            edge = net.edges[eid]
            if edge.is_closed or edge.current_speed_limit <= 0.0:
                cost = float("inf")
                break
            cost += context.cost_function(edge, veh, net, context)

        self.gbest_cost = cost
        if cost == float("inf"):
            # The path is broken. We keep the nodes/edges (in case they recover)
            # but setting cost to infinity lets the swarm naturally override it.
            self.gbest_source = "None"
